"""empty message

迁移 ID: 95cb99f34471
父迁移: 
创建时间: 2026-03-28 23:36:34.366445

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '95cb99f34471'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_access_subjectdata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nonebot_plugin_access_subjectdata')),
    info={'bind_key': 'nonebot_plugin_access'}
    )
    op.create_table('nonebot_plugin_bots_user_private_chat_settings',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('bot_id', sa.String(length=128), nullable=False),
    sa.Column('private_chat_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'bot_id', name=op.f('pk_nonebot_plugin_bots_user_private_chat_settings')),
    info={'bind_key': 'nonebot_plugin_bots'}
    )
    op.create_table('nonebot_plugin_chat_messagequeuecache',
    sa.Column('group_id', sa.String(length=128), nullable=False),
    sa.Column('messages_json', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=False),
    sa.Column('updated_time', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_nonebot_plugin_chat_messagequeuecache')),
    info={'bind_key': 'nonebot_plugin_chat'}
    )
    op.create_table('nonebot_plugin_chat_moonclawconfig',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_nonebot_plugin_chat_moonclawconfig')),
    info={'bind_key': 'nonebot_plugin_chat'}
    )
    op.create_table('nonebot_plugin_chat_note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('context_id', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('keywords', sa.String(length=256), nullable=False),
    sa.Column('created_time', sa.Float(), nullable=False),
    sa.Column('expire_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nonebot_plugin_chat_note')),
    info={'bind_key': 'nonebot_plugin_chat'}
    )
    with op.batch_alter_table('nonebot_plugin_chat_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nonebot_plugin_chat_note_context_id'), ['context_id'], unique=False)

    op.create_table('nonebot_plugin_chat_privatechatsession',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('bot_id', sa.String(length=128), nullable=False),
    sa.Column('last_message_time', sa.Float(), nullable=False),
    sa.Column('last_proactive_message_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_nonebot_plugin_chat_privatechatsession')),
    info={'bind_key': 'nonebot_plugin_chat'}
    )
    op.create_table('nonebot_plugin_larklang_displaysetting',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_nonebot_plugin_larklang_displaysetting')),
    info={'bind_key': 'nonebot_plugin_larklang'}
    )
    op.create_table('nonebot_plugin_larklang_grouplanguagesetting',
    sa.Column('group_id', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_nonebot_plugin_larklang_grouplanguagesetting')),
    info={'bind_key': 'nonebot_plugin_larklang'}
    )
    op.create_table('nonebot_plugin_larklang_languagekeycache',
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('plugin', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('language', 'plugin', 'key', name=op.f('pk_nonebot_plugin_larklang_languagekeycache')),
    info={'bind_key': 'nonebot_plugin_larklang'}
    )
    op.create_table('nonebot_plugin_larkuser_guestuser',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_nonebot_plugin_larkuser_guestuser')),
    info={'bind_key': 'nonebot_plugin_larkuser'}
    )
    op.create_table('nonebot_plugin_larkuser_userdata',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=256), nullable=False),
    sa.Column('register_time', sa.DateTime(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('vimcoin', sa.Float(), nullable=False),
    sa.Column('health', sa.Float(), nullable=False),
    sa.Column('favorability', sa.Float(), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_nonebot_plugin_larkuser_userdata')),
    info={'bind_key': 'nonebot_plugin_larkuser'}
    )
    op.create_table('nonebot_plugin_larkutils_luckvalue',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('luck_value', sa.Integer(), nullable=False),
    sa.Column('generate_date', sa.Date(), nullable=False),
    sa.Column('reroll_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_nonebot_plugin_larkutils_luckvalue')),
    info={'bind_key': 'nonebot_plugin_larkutils'}
    )
    op.create_table('nonebot_plugin_openai_openaimodelconfig',
    sa.Column('config_key', sa.String(length=256), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('config_type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('config_key', name=op.f('pk_nonebot_plugin_openai_openaimodelconfig')),
    info={'bind_key': 'nonebot_plugin_openai'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonebot_plugin_openai_openaimodelconfig')
    op.drop_table('nonebot_plugin_larkutils_luckvalue')
    op.drop_table('nonebot_plugin_larkuser_userdata')
    op.drop_table('nonebot_plugin_larkuser_guestuser')
    op.drop_table('nonebot_plugin_larklang_languagekeycache')
    op.drop_table('nonebot_plugin_larklang_grouplanguagesetting')
    op.drop_table('nonebot_plugin_larklang_displaysetting')
    op.drop_table('nonebot_plugin_chat_privatechatsession')
    with op.batch_alter_table('nonebot_plugin_chat_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nonebot_plugin_chat_note_context_id'))

    op.drop_table('nonebot_plugin_chat_note')
    op.drop_table('nonebot_plugin_chat_moonclawconfig')
    op.drop_table('nonebot_plugin_chat_messagequeuecache')
    op.drop_table('nonebot_plugin_bots_user_private_chat_settings')
    op.drop_table('nonebot_plugin_access_subjectdata')
    # ### end Alembic commands ###
